### PR TITLE
Add support for multiple translated languages in a single mod

### PR DESCRIPTION
**Pull request by Idrinth**
This would allow for a single mod to ship translations into multiple languages, making it automatically use the desired language for texts.

This is not properly tested - just wanted to share the idea before finalizing it.

### CODE REVIEW

**Comment by Cutleast** [comment]
Thanks for contributing!
The developer, [SkyHorizon3](https://github.com/SkyHorizon3), is not at home until the beginning of September, then he will be able to look at your pull request.

**Comment by SkyHorizon3** [comment]
Thank you for your contribution. I'll merge it when you're done. Just finish it in any way, the config code is a mess anyway and needs a proper rewrite soon :D

**Comment by Idrinth** [comment]
> Thank you for your contribution. I'll merge it when you're done. Just finish it in any way, the config code is a mess anyway and needs a proper rewrite soon :D

Will look into building and testing it tomorrow then :) Looking forward to have the multi language option for a few of my mods.

**Comment by Idrinth** [comment]
@SkyHorizon3 seems to work now :) added a few input checks for the ini to prevent issues from outdated ones

**Pull request merged**
